title: Page

fields:
  title:
    label: Title
    type:  text

  description:
    label: Description (150 - 170 characters)
    type:  text
    validate:
      minLength: 150
      maxLength: 170
      - alphanum

  keywords:
    label: Keywords
    type:  text

  text:
    label: Text
    type:  textarea
