title: Page

fields:
  title:
    label: Title
    type:  text

  description:
    label: Description
    type:  text

  keywords:
    label: Keywords
    type:  text

  text:
    label: Text
    type:  textarea
