title: Project

files:
  sortable: true

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 3/4

  year:
    label: Year
    type:  text
    width: 1/4

  description:
    label: Description
    type:  text
    validate:
      min: 150
      max: 170
      - alphanum
      
  keywords:
    label: Keywords
    type:  text

  text:
    label: Text
    type:  textarea

  project:
    label: Project
    type:  text
    width: 1/3

  type:
    label: Type
    type:  text
    width: 1/3

  style:
    label: Style
    type:  text
    width: 1/3

  tags:
    label: Tags
    type: tags
    separator: /

  cover_image:
     label: Cover image (434x424px)
     type: image

  gallery:
    label: Gallery
    type: structure
    fields:
      gallery_image:
        label: Image (1240x698)
        type: image
