title: Site

fields:
  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text

  description:
    label: Description (150 - 170 characters)
    type:  textarea

  copyright:
    label: Copyright
    type:  textarea
